server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/wwq_bs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Segma@157262
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-enums-package: com.example.demo.**.enums

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
